# Generated by Django 2.0.4 on 2018-06-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestasApp', '0003_remove_encuesta_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='encuestasApp.Usuario'),
            preserve_default=False,
        ),
    ]
