# Generated by Django 2.0.4 on 2018-06-09 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('encuestasApp', '0004_auto_20180609_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fechaPub',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 9, 10, 51, 25, 323640, tzinfo=utc), verbose_name='fecha de publicacion'),
            preserve_default=False,
        ),
    ]
